### ISSUE TITLE
Fatal error lors du lancement de la recherche des dernieres versions sur les depots

### ISSUE THREAD

**Issue by Gvx-** [JcDenis/checkStoreVersion#1]
Tout est dans le titre.

Voici le message d'erreur:

` Fatal error: Declaration of csvStore::check($force = true) must be compatible with dcStore::check(bool $force = false): bool in C:\wamp64\www\dc2-plugins\checkStoreVersion\inc\class.csv.store.php on line 20`

version dc: 2.24-dev-r20221201.1616
version PHP 7.4.33

**Comment by JcDenis** [comment]
Sur quelle version de Dotclear ?
On dirait que les signatures de fonctions ont changé depuis la 2.19

**Comment by Philippe-dev** [comment]
Pareil que Gvx avec la même version de dev de dotclear en local :
`Fatal error: Declaration of csvStore::check($force = true) must be compatible with dcStore::check(bool $force = false): bool in /var/.../dotclear/plugins/checkStoreVersion/inc/class.csv.store.php on line 20`

**Comment by JcDenis** [comment]
Raa mais la version courante du plugin n'est pas fait pour Dotclear 2.24
Je vais par contre ajouter un truc pour qu'il ne fonctionne pas au-dessus de 2.23.1. Na.
