### ISSUE TITLE
warning version php

### ISSUE THREAD

**Issue by nanart59** [JcDenis/checkStoreVersion#3]
Note, pour info
Dotclear 2.26.1   /  Version de PHP : 8.2.3

**warning version Dotclear **

```
Check store version 0.2
Cette version ne supporte pas Dotclear > 2.23.1
```
```
Check store version 0.3.1
Cette version ne supporte pas Dotclear > 2.25.3
```

Peut-être un  pb lié à Dotclear/_define (/php >=8.1) ?

**Comment by JcDenis** [comment]
non, ce plugin est mis à jour et est utilisé uniquement ponctuellement pour des changements de versions bien spécifiques de dotclear. Sa dernière utilité était pour le passage de la 2.24 à la 2.25.3 de dotclear. Donc en ce moment il ne sert à rien et ne fonctionne donc pas.

Je changerais peut-être un jour son mode de fonctionnement mais ça m'étonnerait car comme dit au dessus il doit suivre et répondre à des demandes bien spécifiques et ponctuelles.
